T1 = """<table><thead><tr><th>Canada #</th><th>University</th><th>City</th><th>QS 2026 / note</th></tr></thead><tbody><tr><td>1</td><td>McGill University</td><td>Montreal</td><td>27</td></tr><tr><td>2</td><td>University of Toronto</td><td>Toronto</td><td>29</td></tr><tr><td>3</td><td>University of British Columbia</td><td>Vancouver</td><td>40</td></tr><tr><td>4</td><td>University of Alberta</td><td>Edmonton</td><td>=94</td></tr><tr><td>5</td><td>University of Waterloo</td><td>Waterloo</td><td>119</td></tr><tr><td>6</td><td>Western University</td><td>London, ON</td><td>151</td></tr><tr><td>7</td><td>Université de Montréal</td><td>Montreal</td><td>168</td></tr><tr><td>8</td><td>McMaster University</td><td>Hamilton</td><td>173</td></tr><tr><td>9</td><td>Queen's University</td><td>Kingston</td><td>191</td></tr><tr><td>10</td><td>University of Calgary</td><td>Calgary</td><td>211</td></tr><tr><td>11</td><td>University of Ottawa</td><td>Ottawa</td><td>219</td></tr><tr><td>12</td><td>Dalhousie University</td><td>Halifax</td><td>283</td></tr><tr><td>13</td><td>Simon Fraser University</td><td>Burnaby</td><td>308</td></tr><tr><td>14</td><td>York University</td><td>Toronto</td><td>333</td></tr><tr><td>15</td><td>University of Victoria</td><td>Victoria</td><td>358</td></tr><tr><td>16</td><td>University of Saskatchewan</td><td>Saskatoon</td><td>378</td></tr><tr><td>17</td><td>Concordia University</td><td>Montreal</td><td>465</td></tr><tr><td>18</td><td>Université Laval</td><td>Quebec City</td><td>469</td></tr><tr><td>19</td><td>University of Guelph</td><td>Guelph</td><td>504</td></tr><tr><td>20</td><td>University of Windsor</td><td>Windsor</td><td>546</td></tr><tr><td>21</td><td>University of Manitoba</td><td>Winnipeg</td><td>Strong Prairie research option</td></tr><tr><td>22</td><td>Carleton University</td><td>Ottawa</td><td>Capital-city programmes</td></tr><tr><td>23</td><td>Memorial University</td><td>St. John's</td><td>Atlantic value pathway</td></tr><tr><td>24</td><td>Toronto Metropolitan University</td><td>Toronto</td><td>Career-focused urban campus</td></tr><tr><td>25</td><td>University of New Brunswick</td><td>Fredericton</td><td>Atlantic research university</td></tr></tbody></table>"""
T2 = """<table>
<thead><tr><th>University type</th><th>Examples from this top 25</th><th>Best for</th></tr></thead>
<tbody>
<tr><td>Global research flagships</td><td>McGill, Toronto, UBC</td><td>Prestige, broad majors, large alumni networks</td></tr>
<tr><td>Co-op &amp; tech pipelines</td><td>Waterloo, SFU, Carleton (tech)</td><td>Engineering, CS, paid work terms</td></tr>
<tr><td>Medical &amp; health research</td><td>McMaster, Alberta, Dalhousie</td><td>Health sciences, research labs</td></tr>
<tr><td>Francophone excellence</td><td>Montréal, Laval</td><td>French-language degrees, Quebec culture</td></tr>
<tr><td>Value &amp; regional hubs</td><td>Manitoba, Memorial, UNB</td><td>Lower living costs, strong regional ties</td></tr>
</tbody>
</table>"""
