import os

filepath = 'write-for-us/index.html'
with open(filepath, 'r', encoding='utf-8') as f:
    html = f.read()

start_marker = '<article class="article-body">'
end_marker = '</article></section></main>'

start_idx = html.find(start_marker)
end_idx = html.find(end_marker)

if start_idx != -1 and end_idx != -1:
    new_content = '''<article class="article-body">
  
  <p>TopSchoolsRankings is committed to providing independent, objective, and transparent education research. As part of our mission, we occasionally publish editorial contributions from verified education professionals, admissions experts, and current students.</p>

  <p>Please note that we maintain strict editorial standards. This page outlines our requirements for editorial submissions.</p>

  <h2>Content Guidelines and Acceptable Topics</h2>
  <p>We accept high-quality, deeply researched, and highly specific editorial content related to:</p>
  <ul>
    <li>University and boarding school admissions strategies</li>
    <li>International student experiences and visa pathways</li>
    <li>Academic curriculum comparisons (e.g., A-Levels vs. IB)</li>
    <li>Financial aid, scholarship, and student budget planning</li>
  </ul>
  <p><strong>Originality:</strong> All submissions must be 100% original. We do not accept syndicated content, plagiarized text, or articles that have been published elsewhere on the internet. All submissions undergo rigorous plagiarism checks.</p>
  
  <p><strong>Factual Accuracy and Sources:</strong> You must verify every factual claim. All statistics, dates, and admissions data must be attributed to primary authoritative sources (e.g., official school websites, government portals like GOV.UK or the US Department of Education). Do not fabricate statistics, reviews, or testimonials.</p>

  <h2>What We Do Not Accept</h2>
  <p>TopSchoolsRankings is an independent educational publisher, not a guest-post marketplace. We strictly reject:</p>
  <ul>
    <li>Promotional or spam content</li>
    <li>Articles designed solely to generate backlinks or manipulate search engine rankings</li>
    <li>Unsubstantiated or exaggerated claims</li>
    <li>Content generated by AI without significant human editorial oversight and fact-checking</li>
  </ul>
  <p>You must fully disclose any conflicts of interest (e.g., if you are employed by a school or admissions agency you are writing about).</p>

  <h2>Our Editorial Process and Terms</h2>
  <p>Submitting an article does not guarantee publication. Our editorial team reviews every submission for accuracy, clarity, and style alignment with our <a href="/editorial-policy/">Editorial Policy</a> and <a href="/ranking-methodology/">Ranking Methodology</a>.</p>
  
  <p>By submitting content, you acknowledge that:</p>
  <ul>
    <li>We reserve the right to heavily edit, revise, or reject submissions for factual accuracy and style.</li>
    <li><strong>Publication is not guaranteed.</strong></li>
    <li><strong>We do not guarantee dofollow backlinks</strong>, commercial placement, or favorable ranking status for any linked entity.</li>
    <li>There is no fee paid by us for contributions, nor do we accept payment to bypass our editorial standards.</li>
  </ul>

  <h2>How to Submit</h2>
  <p>To submit a pitch or completed draft, please contact our editorial team via our official <a href="/contact-us/">Contact Us</a> page. Include a brief summary of your expertise and the proposed topic.</p>

'''

    final_html = html[:start_idx] + new_content + html[end_idx:]
    
    # Remove the noindex tag I added earlier, putting it back to index
    final_html = final_html.replace('<meta name="robots" content="noindex, follow">', '<meta name="robots" content="index, follow">')
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(final_html)
    print("Successfully replaced content and restored index tag.")
else:
    print(f"Could not find markers. start: {start_idx}, end: {end_idx}")