import re
import os

updates = {
    'unsw-sydney-guide-for-international-students-2026': '''<section class="faq-section"><h2>Frequently Asked Questions About UNSW Sydney</h2><details><summary>What is the UNSW 3+ Academic Calendar?</summary><p>Unlike traditional two-semester systems, UNSW operates on a unique trimester model (UNSW 3+). Students take three subjects over three 10-week terms, plus an optional intensive summer term. This offers greater flexibility to fast-track a degree, take lighter loads, or incorporate internships, though it creates a very fast-paced learning environment.</p></details><details><summary>Is UNSW better than the University of Sydney?</summary><p>Both are elite Group of Eight universities, but they have different strengths. UNSW is historically renowned for STEM, Engineering, Business, and Innovation (often producing the most startup founders in Australia). The University of Sydney is traditionally famous for Arts, Humanities, Law, and Medicine. Your choice should depend on your specific major.</p></details><details><summary>Where is the main campus located?</summary><p>The primary UNSW campus is in Kensington, a vibrant suburb in Sydney's eastern suburbs. It is ideally situated just 15 minutes away from the famous Coogee Beach and about 20 minutes from the Sydney Central Business District (CBD) via the Light Rail network.</p></details></section>''',

    'mcgill-university-for-international-students-the-ultimate-2026-admissions-guide': '''<section class="faq-section"><h2>Frequently Asked Questions About McGill University</h2><details><summary>Do I need to speak French to attend McGill?</summary><p>No. McGill is an English-language university located in the heart of Montreal, Quebec (a predominantly French-speaking province). All classes, exams, and university services are conducted in English. However, learning conversational French is highly recommended to fully enjoy Montreal and to secure off-campus internships.</p></details><details><summary>Why is McGill's tuition different for different students?</summary><p>McGill has a complex, three-tiered tuition structure based on residency. Quebec residents pay the lowest fees, out-of-province Canadian citizens pay higher fees, and international students pay deregulated international tuition. Recent provincial government changes have increased fees for out-of-province Canadians, but international fees remain competitive compared to US private universities.</p></details><details><summary>How does the admissions cutoff work?</summary><p>McGill admissions are notoriously transparent and strictly numbers-based. The university publishes historical minimum grade cutoffs (e.g., specific high school GPAs or IB scores) required for admission into each specific faculty. If you exceed the published cutoff, you are generally guaranteed admission; if you fall below it, you will likely be rejected.</p></details></section>''',

    'branksome-hall-torontos-ib-girls-boarding-school': '''<section class="faq-section"><h2>Frequently Asked Questions About Branksome Hall</h2><details><summary>What is the International Baccalaureate (IB) advantage at Branksome?</summary><p>Branksome Hall is the only all-girls, all-IB independent school in Toronto. Every student, from Junior Kindergarten through Grade 12, participates in the IB curriculum (PYP, MYP, and the rigorous IB Diploma Programme). This provides a globally recognized, inquiry-based education that is highly sought after by top-tier universities worldwide.</p></details><details><summary>Does Branksome Hall accept international boarders?</summary><p>Yes, the boarding program at Branksome Hall begins in Grade 7 and houses students from over a dozen different countries. The state-of-the-art boarding facilities are located directly on the school's beautiful 13-acre campus in the heart of Toronto's upscale Rosedale neighborhood.</p></details><details><summary>What is the school's approach to STEM?</summary><p>Despite being a traditional girls' school, Branksome heavily emphasizes Science, Technology, Engineering, and Math (STEM). The campus features a dedicated Athletics and Wellness Centre and a cutting-edge Innovation Centre, encouraging girls to pursue robotics, coding, and advanced sciences in a highly supportive environment.</p></details></section>''',

    'california-institute-of-technology-acceptance-rate-2026-how-hard-is-it-to-get-into-caltech': '''<section class="faq-section"><h2>Frequently Asked Questions About Caltech Admissions</h2><details><summary>How is Caltech different from MIT?</summary><p>While both are premier STEM institutes, Caltech is dramatically smaller. Caltech has fewer than 1,000 undergraduate students (compared to MIT's ~4,600). This incredibly small size results in a roughly 3:1 student-to-faculty ratio, allowing undergraduates to engage in high-level research with Nobel laureates almost immediately.</p></details><details><summary>Is Caltech test-blind or test-optional?</summary><p>Caltech previously implemented a test-blind policy during the pandemic, but policies evolve rapidly. Always check the official Caltech admissions page for the current cycle. Historically, Caltech students boast some of the highest perfect or near-perfect SAT and ACT math scores in the world.</p></details><details><summary>What is the Core Curriculum at Caltech?</summary><p>The Core at Caltech is legendary for its extreme rigor. Regardless of your major, every student must pass multiple terms of intensive calculus, classical mechanics, electromagnetism, chemistry, and biology, alongside humanities courses. The workload is immense, requiring intense collaboration among students.</p></details></section>''',

    'melbourne-grammar-school-a-complete-overview': '''<section class="faq-section"><h2>Frequently Asked Questions About Melbourne Grammar</h2><details><summary>Is Melbourne Grammar a co-educational school?</summary><p>Melbourne Grammar School is co-educational only at the primary level (Grimwade House, Prep to Year 6). From Year 7 through Year 12 (Wadhurst and Senior School), it is exclusively an all-boys school.</p></details><details><summary>What curriculum does Melbourne Grammar offer?</summary><p>In the Senior School, students study the Victorian Certificate of Education (VCE), which is the standard high school qualification in the state of Victoria. The school consistently produces some of the highest ATAR scores in the state, with many boys going on to elite universities globally.</p></details><details><summary>How competitive is the boarding program?</summary><p>Melbourne Grammar maintains a highly prestigious boarding house for roughly 120 boys, starting from Year 7. Places are highly competitive, heavily sought after by rural families across Australia and international students. Applications for boarding should be submitted years in advance.</p></details></section>''',

    'algoma-university-for-international-students-admissions-fees-courses-visa-guide': '''<section class="faq-section"><h2>Frequently Asked Questions About Algoma University</h2><details><summary>Where are Algoma's campuses located?</summary><p>Algoma University has three distinct campuses in Ontario, Canada. The main historic campus is in Sault Ste. Marie (offering a traditional, nature-surrounded university experience), with satellite campuses in Brampton (a massive hub for international students near Toronto) and Timmins.</p></details><details><summary>Is Algoma affordable for international students?</summary><p>Yes, Algoma is widely recognized as one of the most affordable public universities in Ontario. International tuition is significantly lower than at major universities in Toronto or Vancouver, making it a highly attractive option for students seeking a cost-effective pathway to a Canadian degree and PGWP.</p></details><details><summary>What are the most popular programs at Algoma?</summary><p>Algoma specializes in undergraduate education. For international students, the most popular programs are Computer Science (especially at the Brampton campus due to the local tech industry), Business Administration, and specialized certificate programs designed for fast-track career entry.</p></details></section>''',

    'how-to-get-into-phillips-exeter-academy-2026-admissions-fees-expert-strategies': '''<section class="faq-section"><h2>Frequently Asked Questions About Phillips Exeter Academy</h2><details><summary>What is the Harkness Method?</summary><p>The Harkness Method is the defining feature of a Phillips Exeter education. Instead of a teacher lecturing from the front, classes consist of 12 students sitting around an oval table leading a discussion. The teacher acts as a facilitator, and students are graded on their ability to analyze, debate, and collaborate respectfully.</p></details><details><summary>How hard is the SSAT requirement?</summary><p>Admission to Exeter is highly competitive (often below a 15% acceptance rate), and the Secondary School Admission Test (SSAT) is a critical component. Successful applicants typically score in the 90th percentile or above. However, Exeter practices holistic admissions, so exceptional talent in arts, athletics, or leadership can sometimes balance a lower score.</p></details><details><summary>Is financial aid available for international students?</summary><p>Yes, Phillips Exeter has an incredibly large endowment and is one of the few boarding schools committed to meeting 100% of the demonstrated financial need for all admitted students, including international applicants. Admissions are strictly need-blind.</p></details></section>''',

    'how-technology-is-supporting-school-students-beyond-the-classroom': '''<section class="faq-section"><h2>Frequently Asked Questions About EdTech Integration</h2><details><summary>Does more screen time negatively impact student wellbeing?</summary><p>This is a major concern for educators and parents. While passive screen time (like endless scrolling) is linked to negative wellbeing, active, purpose-driven screen time (like coding, interactive learning, and collaborative projects) can be highly beneficial. The key is strict digital boundaries and balancing technology with physical, outdoor activities.</p></details><details><summary>How is AI changing homework and assessment?</summary><p>Generative AI (like ChatGPT) is forcing schools to rethink homework entirely. Instead of assigning essays that can be easily generated by AI, teachers are moving towards "flipped classrooms," in-class oral assessments, and project-based learning where AI is used as a brainstorming tool rather than a shortcut.</p></details><details><summary>Are digital learning platforms secure?</summary><p>Data privacy is critical. Reputable school districts only use enterprise-grade platforms (like Google Workspace for Education or Canvas) that comply with strict student privacy laws (like COPPA and FERPA in the US). Parents should always have the right to know what data is being collected on their child.</p></details></section>''',

    'james-ruse-agricultural-high-school-entry-guide-2026-hsc-results-cutoff-how-to-get-in': '''<section class="faq-section"><h2>Frequently Asked Questions About James Ruse Entry</h2><details><summary>Why is James Ruse so famous in NSW?</summary><p>James Ruse Agricultural High School has dominated the New South Wales HSC (Higher School Certificate) rankings for almost three decades, consistently placing first in the state. It produces an extraordinarily high number of students who achieve a perfect 99.95 ATAR and go on to study Medicine and Law.</p></details><details><summary>Do students actually have to study agriculture?</summary><p>Yes. Despite its reputation as an academic powerhouse in mathematics and science, it remains an agricultural high school. Agriculture is a compulsory subject for all students from Year 7 through to Year 10, and students are required to participate in practical farm work on the school's working farm.</p></details><details><summary>What is the minimum score required for entry?</summary><p>Entry is determined strictly by the NSW Selective High School Placement Test. Because it is the most sought-after school in the state, the cutoff score is exceptionally high. While the exact calculated profile score varies slightly each year based on the cohort's performance, applicants generally need to score in the absolute top tier (often above 115+ out of 120 in the new test format).</p></details></section>'''
}

for folder_name, new_content in updates.items():
    filepath = os.path.join(folder_name, 'index.html')
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            html = f.read()
        
        if '</article>' in html and new_content not in html:
            html = html.replace('</article>', new_content + '\n</article>')
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(html)
            print(f"Updated {filepath}")
        else:
            print(f"Already updated or missing </article> in {filepath}")
    else:
        print(f"Missing file {filepath}")