import re

with open('complete-university-cost-comparison-checklist/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

new_content = '''<div class="answer-box"><span>Quick answer</span><p>Compare the net cost for the full degree duration, not just one year of advertised tuition. Include compulsory university fees, off-campus housing, food, local transport, mandatory health insurance, equipment, visa application costs, and realistic funding. Always add a 5-10% contingency buffer for annual tuition increases and currency exchange fluctuations.</p></div><div class="editor-note"><strong>Editorial note:</strong> Education, admissions, fees, and immigration rules can change rapidly. Always check the linked official university bursar or financial aid source again before making financial commitments.</div>

<section><h2>Sticker Price vs. Net Cost: Understanding the Baseline</h2><p>The single biggest financial mistake students and parents make is looking at a university's advertised "sticker price" for tuition and assuming that is the final bill. To accurately compare university costs, you must calculate the <strong>Net Cost</strong>.</p><p>Net Cost is defined as the total cost of attendance (tuition, fees, room, and board) minus any guaranteed grants or scholarships that you do not have to pay back. If University A charges ,000 but offers a guaranteed ,000 merit scholarship, its net cost (,000) is cheaper than University B, which charges ,000 but offers zero financial aid.</p><p>Furthermore, a three-year degree (common in the UK and Australia) and a four-year degree (standard in the US and Canada) cannot be compared using annual tuition alone. You must create a full-program budget. For example, £20,000 per year for 3 years (£60,000 total) is significantly cheaper than ,000 per year for 4 years (,000 total).</p></section>

<section><h2>Identify the "Hidden" University-Billed Charges</h2><p>Tuition is just the baseline. When reviewing your financial statement, look for mandatory fees that are often buried in the fine print. Ask the financial aid office whether these fees are expected to rise for continuing students. Record every single line item:</p><ul><li><strong>Mandatory Student Fees:</strong> Registration fees, student-service or student union fees, technology fees, and examination fees. These can add ,000 to ,000 annually.</li><li><strong>Health Insurance:</strong> International students are almost always required to purchase specific health insurance. In the UK, this is the Immigration Health Surcharge (IHS); in the US and Canada, it is a mandatory university health plan.</li><li><strong>Program-Specific Costs:</strong> Laboratory fees for science students, studio fees for art/design students, or mandatory fieldwork travel expenses.</li><li><strong>Orientation and International Fees:</strong> Many universities charge a one-time "International Student Orientation Fee" or SEVIS administration fee (in the US) during the first semester.</li></ul></section>

<section><h2>Estimate Living Costs Realistically (Not Just the National Average)</h2><p>University websites often provide a "suggested living cost" figure, but these are frequently underestimated or based on national averages rather than the specific campus neighborhood. Build a month-by-month estimate for your actual lifestyle:</p><p>Include initial setup costs that are often forgotten: a housing deposit (usually 1-2 months' rent), winter clothing, bedding, kitchen items, and local transport setup. International students must also factor in annual round-trip flights home, visa renewal fees, mandatory medical checks, and biometric document costs.</p><p><strong>Accommodation choices drastically swing this budget:</strong> Compare the cost of a shared off-campus apartment (factor in Wi-Fi, water, heating, and 12-month leases) versus an on-campus dorm (which may force you to buy an expensive meal plan but only covers 9 months of the academic year).</p></section>

<section><h2>Separate Confirmed Aid from "Possible" Aid</h2><p>When budgeting, subtract grants and scholarships <strong>only</strong> when they are guaranteed in writing on your official financial aid award letter. Keep competitive scholarships (those you still have to apply or interview for) in a completely separate scenario.</p><p>Record the renewal conditions for any scholarships. Does it require maintaining a 3.5 GPA? Must you remain enrolled full-time? If the university raises tuition by 4% next year, will your scholarship increase by 4% to match it, or is it a fixed dollar amount? (Usually, it is fixed, meaning your out-of-pocket costs will increase every year).</p><p>For US comparisons, tools like the College Scorecard provide excellent aggregated context on average debt and aid, but your individual official aid offer is the only document that legally matters.</p></section>

<section><h2>Factor in Inflation and Currency Fluctuations</h2><p>Universities rarely lock in tuition rates for all four years. Historically, tuition and campus housing costs rise by 3% to 5% every single year due to inflation. Build a 5% compounding increase into your year 2, year 3, and year 4 budgets.</p><p>If you are an international student, currency fluctuation is your biggest hidden risk. If your home currency drops by 10% against the US Dollar or British Pound, your degree just became 10% more expensive overnight. Keep the original currency beside each figure in your spreadsheet, and always budget a 10% currency contingency fund.</p></section>

<section><h2>Run Three Budget Scenarios</h2><p>A financial stress test shows whether your education plan survives if your assumptions are wrong. Never rely on part-time work income to pay your core tuition—student visas strictly limit work hours, and finding a job is never guaranteed.</p><ul><li><strong>Expected Scenario:</strong> The most realistic tuition, housing, and funding assumptions.</li><li><strong>Optimistic Scenario:</strong> Confirmed savings, such as winning a competitive scholarship or securing cheaper shared housing.</li><li><strong>Stress-Test Scenario:</strong> Maximum tuition increases, higher off-campus rent, and an adverse currency exchange movement of 10%. If you cannot survive the stress test, the university is a high financial risk.</li></ul></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>What is the difference between Tuition and Cost of Attendance (COA)?</summary><p>Tuition is simply the academic charge for instruction and classes. The Cost of Attendance (COA) is a broader, legally regulated estimate that includes tuition, mandatory fees, housing, food, books, transport, and personal expenses. Financial aid in the US is based on the COA, not just tuition.</p></details><details><summary>Should a competitive scholarship be deducted from my budget before it is awarded?</summary><p>No. Put unconfirmed or competitive scholarships in an "optimistic" scenario. Your core baseline budget must rely only on funds you already have or guaranteed aid.</p></details><details><summary>Can I use my student loans or financial aid to pay for off-campus rent?</summary><p>Generally, yes. If your financial aid or student loans exceed your direct university-billed charges (tuition and fees), the university will issue you a "refund" check for the credit balance. You can use this money to pay for off-campus rent, groceries, and textbooks.</p></details><details><summary>How much contingency should an international student add?</summary><p>While there is no universal percentage, financial advisors typically recommend a 10% contingency buffer to absorb unexpected tuition hikes, medical emergencies, and currency exchange rate volatility.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026. Please verify directly with official portals for the most up-to-date regulations.</p><ul><li><a href="https://collegescorecard.ed.gov/" rel="noopener noreferrer" target="_blank">US Department of Education: College Scorecard Data</a></li><li><a href="https://www.ucas.com/applying/after-you-apply/clearing-and-results-day/after-results-day/preparing-for-your-studies" rel="noopener noreferrer" target="_blank">UCAS: Budgeting and Preparing for Studies</a></li><li><a href="https://w05.educanada.ca/" rel="noopener noreferrer" target="_blank">EduCanada: Program and Cost Search</a></li></ul></section>
'''

start_marker = '<article class="article-body">'
end_marker = '<div class="author-bio-box"'

start_idx = html.find(start_marker) + len(start_marker)
end_idx = html.find(end_marker)

if start_idx != -1 and end_idx != -1:
    updated_html = html[:start_idx] + new_content + html[end_idx:]
    with open('complete-university-cost-comparison-checklist/index.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)
    print("Cost article successfully updated!")
else:
    print("Markers not found!")