import re
import os

updates = {
    'top-high-schools-in-england-rankings-guide': '''<section class="faq-section"><h2>Frequently Asked Questions About English High Schools</h2><details><summary>What is the difference between an independent school and a grammar school?</summary><p>In England, an independent (or private) school charges tuition fees and is not funded by the government (e.g., Eton, Harrow). A grammar school is a state-funded public school that selects its students based on academic ability, usually via the 11+ entrance exam. Both often produce exceptional GCSE and A-Level results.</p></details><details><summary>What are Ofsted ratings?</summary><p>Ofsted is the government body that inspects and regulates schools in England. Schools are rated on a scale: Outstanding, Good, Requires Improvement, or Inadequate. While an 'Outstanding' rating is prestigious, parents should read the full report, as a rating focuses heavily on safeguarding and management, not just academic league tables.</p></details><details><summary>Do rankings include both A-Levels and the IB?</summary><p>This is a major flaw in many national league tables. Most traditional rankings are heavily weighted toward A-Level results (the standard UK qualification). Schools that exclusively or predominantly offer the International Baccalaureate (IB), such as Sevenoaks School, are often excluded or improperly ranked in standard newspaper tables.</p></details></section>''',

    'harvard-university-admissions-guide-for-international-students': '''<section class="faq-section"><h2>Frequently Asked Questions About Harvard Admissions</h2><details><summary>Does Harvard have quotas for international students?</summary><p>Officially, Harvard does not have strict numerical quotas for any nationality. However, the international acceptance rate is historically much lower than the domestic rate. International students typically make up about 12% to 15% of the admitted undergraduate class each year.</p></details><details><summary>Are international applicants eligible for financial aid?</summary><p>Yes! Harvard is one of the very few US universities that is completely 'need-blind' for all applicants, regardless of citizenship. If you are admitted, Harvard guarantees to meet 100% of your demonstrated financial need, which can include full tuition, room, board, and even travel expenses for low-income international students.</p></details><details><summary>Does Harvard require the TOEFL or IELTS?</summary><p>If your native language is not English and your high school instruction was not in English, Harvard strongly recommends submitting English proficiency scores. However, a high score on the SAT Evidence-Based Reading and Writing section can often demonstrate sufficient fluency without a separate test.</p></details></section>''',

    'douglas-college-canada-admissions-fees-courses-university-transfer-guide-for-international-students': '''<section class="faq-section"><h2>Frequently Asked Questions About Douglas College</h2><details><summary>Where is Douglas College located?</summary><p>Douglas College has two main campuses located in Metro Vancouver, British Columbia: the New Westminster Campus and the Coquitlam Campus. Both are situated directly on the SkyTrain transit line, providing students with rapid, incredibly convenient access to downtown Vancouver.</p></details><details><summary>How does the University Transfer program work?</summary><p>The University Transfer program is Douglas College's biggest draw. Students can complete their first two years of a bachelor's degree at Douglas (paying much lower college tuition and enjoying smaller class sizes) and then seamlessly transfer those credits directly into the third year of major research universities like UBC or Simon Fraser University (SFU).</p></details><details><summary>Can international students get a PGWP after studying at Douglas?</summary><p>Yes. Because Douglas College is a public, government-funded Designated Learning Institution (DLI), international students who complete an eligible degree, diploma, or certificate program can apply for a Post-Graduation Work Permit (PGWP) to live and work in Canada.</p></details></section>''',

    'top-20-uk-boarding-schools-for-international-students': '''<section class="faq-section"><h2>Frequently Asked Questions About UK Boarding Schools</h2><details><summary>What is a 'Guardian' and why do international students need one?</summary><p>UK law requires that any international student under the age of 18 studying at a boarding school must have an educational guardian based in the UK. The guardian acts in place of the parents for emergencies, attends parent-teacher meetings, and hosts the student during 'exeat' weekends and half-term holidays when the dorms close.</p></details><details><summary>What is the difference between full, weekly, and flexi boarding?</summary><p>Full boarders stay at the school seven days a week, going home only for major holidays. Weekly boarders stay at school Monday through Friday and go home on weekends. Flexi boarding allows day students to sleep at the school occasionally (e.g., one or two nights a week) when they have late sports or early rehearsals.</p></details><details><summary>How much does a top UK boarding school cost?</summary><p>Elite UK boarding schools (like Winchester, Wycombe Abbey, or Eton) are extremely expensive. International families should budget between £40,000 to £55,000 per year for tuition and boarding fees, plus additional costs for uniforms, trips, and guardianship fees.</p></details></section>''',

    'university-of-edinburgh-admissions-guide-international-students': '''<section class="faq-section"><h2>Frequently Asked Questions About the University of Edinburgh</h2><details><summary>How long is a degree at Edinburgh compared to English universities?</summary><p>Scotland has a different educational system than England. An undergraduate Honours degree at the University of Edinburgh typically takes four years to complete, whereas an Honours degree in England (like at Oxford or UCL) takes three years. This extra year allows Scottish students to study a wider variety of subjects before specializing.</p></details><details><summary>Is guaranteed accommodation provided for international students?</summary><p>Yes, the University of Edinburgh guarantees an offer of university-owned accommodation to all new, single undergraduate international students in their first year, provided they apply by the required deadline and hold an unconditional firm offer.</p></details><details><summary>What is the 'Fringe' and how does it affect students?</summary><p>The Edinburgh Festival Fringe is the world's largest arts festival, taking over the city every August. While the festival brings incredible energy, comedy, and culture, it also causes a massive spike in short-term rent prices. Students arriving early in August must secure housing well in advance to avoid exorbitant costs.</p></details></section>''',

    'top-10-universities-in-canada-for-engineering-co-op': '''<section class="faq-section"><h2>Frequently Asked Questions About Canadian Engineering Co-ops</h2><details><summary>What exactly is a 'co-op' in Canada?</summary><p>Co-operative education (co-op) is a structured program where students alternate between academic study terms and paid, full-time work terms in their field of study. Unlike a summer internship, co-op is formally integrated into the degree, and students graduate with 1 to 2 years of professional engineering experience.</p></details><details><summary>Is a co-op degree longer than a standard degree?</summary><p>Yes. Because you are adding multiple 4-month work terms to your schedule, an engineering co-op degree typically takes 5 years to complete instead of the standard 4 years. However, the work experience and salary earned make the extra year highly worthwhile.</p></details><details><summary>Can international students participate in Canadian co-ops?</summary><p>Absolutely. International students enrolled in a mandatory or optional co-op program must apply for a specific Co-op Work Permit from the Canadian government, which allows them to work full-time off-campus during their designated work terms.</p></details></section>''',

    '2026-selective-school-exam-the-ultimate-guide-for-nsw-parents': '''<section class="faq-section"><h2>Frequently Asked Questions About the NSW Selective Exam</h2><details><summary>When should my child start preparing for the exam?</summary><p>Most students sit the exam in March of Year 6. To avoid extreme burnout, educational psychologists generally recommend beginning steady, low-pressure familiarization in mid-Year 5. Cramming heavily in the weeks prior is often counterproductive and drastically increases student anxiety.</p></details><details><summary>Are private tutoring colleges necessary?</summary><p>No. While many parents use tutoring colleges to provide structure and practice exams, the NSW Department of Education explicitly designs the new test format to assess higher-order thinking and problem-solving, making it much harder to "coach" or rote-learn than past exams. Consistent reading and critical thinking practice at home is equally valid.</p></details><details><summary>What happens if my child is sick on the day of the exam?</summary><p>If a student is genuinely ill, parents must immediately notify the Selective Education Unit and submit an Illness/Misadventure claim with robust medical evidence (a doctor's certificate). The department has strict protocols for assessing these cases, often relying on the student's primary school assessment scores if the claim is approved.</p></details></section>''',

    'university-of-british-columbia-admissions-2026-the-ultimate-guide-for-international-students': '''<section class="faq-section"><h2>Frequently Asked Questions About UBC Admissions</h2><details><summary>What is the difference between the Vancouver and Okanagan campuses?</summary><p>UBC operates two main campuses. UBC Vancouver (UBCV) is the historic, massive campus located on the coast, known for intense research output and a bustling urban environment. UBC Okanagan (UBCO) in Kelowna is smaller, more intimate, and often has slightly more accessible admission averages while still granting the exact same prestigious UBC degree.</p></details><details><summary>What is the UBC Personal Profile?</summary><p>Unlike many Canadian universities that only look at grades, UBC requires all applicants to submit a Personal Profile. This consists of several short essay questions detailing your extracurricular activities, leadership experiences, and how you have overcome challenges. It is a critical component of the admission decision.</p></details><details><summary>Does UBC require the SAT/ACT for US applicants?</summary><p>As of recent admissions cycles, UBC has moved away from requiring the SAT or ACT for American applicants, aligning more closely with the test-optional movement. Instead, they heavily weigh your high school transcript, AP/IB scores, and the depth of your Personal Profile.</p></details></section>''',

    'university-of-oxford-admissions-guide-2026-international-students': '''<section class="faq-section"><h2>Frequently Asked Questions About Oxford Admissions</h2><details><summary>Can I apply to both Oxford and Cambridge in the same year?</summary><p>No. Under the UCAS (Universities and Colleges Admissions Service) rules, undergraduate applicants are strictly forbidden from applying to both the University of Oxford and the University of Cambridge in the same admissions cycle. You must choose one.</p></details><details><summary>What is a 'college' at Oxford?</summary><p>Oxford is a collegiate university. When you apply, you don't just apply to the central university; you apply to a specific College (like Magdalen, Christ Church, or Balliol). Your college is where you live, eat, socialize, and receive your small-group academic tutorials. The central university provides the lectures and awards the final degree.</p></details><details><summary>How important is the Oxford admissions interview?</summary><p>The interview is arguably the most critical and defining part of the Oxford admissions process. It is not a behavioral or 'getting-to-know-you' chat. It is a rigorous, academic mock-tutorial where professors will push you to solve complex, unseen problems in your subject area to see how your brain processes new information.</p></details></section>'''
}

for folder_name, new_content in updates.items():
    filepath = os.path.join(folder_name, 'index.html')
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            html = f.read()
        
        if '</article>' in html and new_content not in html:
            html = html.replace('</article>', new_content + '\n</article>')
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(html)
            print(f"Updated {filepath}")
        else:
            print(f"Already updated or missing </article> in {filepath}")
    else:
        print(f"Missing file {filepath}")