import re

with open('how-to-verify-university-accreditation-before-you-apply/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

new_content = '''<div class="answer-box"><span>Quick answer</span><p>Verify a university's accreditation in the official government or educational regulator database for that specific country (e.g., the US Department of Education, UK Office for Students, or Australian CRICOS). Additionally, confirm that your exact degree program holds programmatic accreditation if required for your profession. A high ranking, a social media profile, or an agent's brochure is never proof of accreditation.</p></div><div class="editor-note"><strong>Editorial note:</strong> Education, admissions, fees, and immigration rules change frequently. Check the linked official sources again before applying or paying any tuition deposits.</div>

<section><h2>Why Accreditation Needs a Separate Check</h2><p>Accreditation and official recognition determine whether your degree will be legally accepted by employers, licensing bodies, other universities (for master's or PhD progression), and immigration authorities. A university may be a legitimate business, but if it lacks recognized academic accreditation, your degree could be essentially worthless.</p><p>Furthermore, there is a massive difference between <strong>Institutional Accreditation</strong> (the whole university is legitimate) and <strong>Programmatic Accreditation</strong> (a specific professional course meets industry standards). For example, a legitimate university might offer an engineering degree, but if it lacks ABET accreditation in the US or Engineering Council approval in the UK, you may not be legally allowed to work as a licensed engineer.</p><p>Do not treat a polished website, a high Google search position, a "ranking badge," or the word "International" in the university's name as evidence. Start with an official government database, record what you find, and demand the institution explain any mismatches in writing before you pay a deposit.</p></section>

<section><h2>Beware of Diploma Mills and Fake Accreditors</h2><p>The internet is filled with "diploma mills"—unaccredited institutions that award degrees for a fee with little to no academic work required. To appear legitimate, these fake universities often create their own fake accreditation agencies.</p><p>If a university website proudly claims to be accredited by the "International Council of Global Higher Education" (or a similarly official-sounding but fake body), it is a major red flag. Always cross-reference the accreditation agency itself with the national government's list of recognized accreditors (such as CHEA in the United States).</p></section>

<section><h2>United States: Department of Education & CHEA</h2><p>The US system is highly decentralized. The government does not accredit schools directly; instead, it recognizes independent accreditation agencies. There are historically two types: Regional (widely accepted, highly prestigious) and National (often for vocational or for-profit schools, with credits that may not transfer to regional schools).</p><p>To verify a US institution:</p><ul><li>Use the <a href="https://ope.ed.gov/dapip/" target="_blank" rel="noopener">U.S. Department of Education's Database of Accredited Postsecondary Institutions and Programs (DAPIP)</a>.</li><li>Check the <a href="https://www.chea.org/" target="_blank" rel="noopener">Council for Higher Education Accreditation (CHEA)</a> database.</li></ul><p>Search the institution's legal name and confirm the accrediting agency shown in the record. If the university is not in these databases, do not enroll.</p></section>

<section><h2>United Kingdom: Recognized Bodies and the OfS</h2><p>In the UK, universities can only award degrees if they are officially recognized by the UK government (historically through a Royal Charter or an Act of Parliament). These are known as "Recognized Bodies."</p><ul><li>Check the official <strong>Office for Students (OfS)</strong> Register to ensure the university is registered to operate and award degrees in England (with similar registers for Scotland, Wales, and Northern Ireland).</li><li>Use the official course and provider information available through <strong>UCAS</strong> and <strong>Discover Uni</strong>.</li><li>For regulated careers (like Law, Medicine, or Accounting), check the relevant professional body's approved-program list (e.g., the SRA for Law, GMC for Medicine).</li></ul><p>If you need a UK Student Visa, you must also verify that the university is a "Licensed Sponsor" on the official GOV.UK register before accepting an offer.</p></section>

<section><h2>Canada and Australia: Verifying International Study Eligibility</h2><p>If you are an international student, domestic accreditation is only half the battle. The institution must be explicitly authorized to host foreign students.</p><ul><li><strong>Canada:</strong> International applicants must confirm that the school appears on the current <strong>Designated Learning Institution (DLI)</strong> list. Crucially, you must check if the exact campus and program you are applying for are eligible for the Post-Graduation Work Permit (PGWP).</li><li><strong>Australia:</strong> Search <strong>CRICOS</strong>—the Australian Government register of providers and courses offered to international students on student visas. You must match the exact provider code, course code, campus location, and duration.</li></ul></section>

<section><h2>A Seven-Step Verification Checklist</h2><p>Before transferring any tuition funds, complete this checklist:</p><ol><li>Search the official national regulator or government database using the university's legal corporate name.</li><li>Check the specific accreditation agency against the country's list of approved accreditors.</li><li>Match the exact campus location, program title, qualification level, and delivery mode (online vs. on-campus).</li><li>Confirm if your specific profession requires programmatic accreditation, and check the professional body's database.</li><li>Verify visa eligibility (DLI, CRICOS, or UK Sponsor License) separately on the relevant government website.</li><li>Open the institution's own course page and note the date you checked it.</li><li>Save screenshots, emails, and links with your application records in case of future disputes.</li></ol></section>

<section><h2>Red Flags That Justify Pausing</h2><p>Pause your application if the name in the official database differs from the name on your offer letter. Stop immediately if the education agent refuses to provide a CRICOS or DLI program code, if the institution pressures you to pay via personal bank transfer immediately, or if employment and immigration outcomes are promised as guaranteed.</p></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Is a university ranking proof of accreditation?</summary><p>Absolutely not. Rankings (like QS or THE) are editorial, analytical, or commercial comparisons. Accreditation is a legal, regulatory status that must be checked with the relevant government database.</p></details><details><summary>Should I verify the specific program as well as the university?</summary><p>Yes. Professional courses (Nursing, Engineering, Architecture), branch campuses, and different study modes (online vs. in-person) can have entirely separate approvals or recognition implications.</p></details><details><summary>Are online degrees accredited the same way as on-campus degrees?</summary><p>Yes, legitimate online degrees awarded by recognized universities hold the exact same institutional accreditation as their on-campus equivalents. However, some professional licensing boards may have restrictions on online lab work or clinical hours, so check with your local industry board.</p></details><details><summary>What if the official record and my offer letter do not match?</summary><p>Do not pay any deposit. Demand that the institution or agent explains the difference in writing, and independently contact the relevant accreditation authority to confirm the correct status.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026. Please verify directly with official portals for the most up-to-date regulations.</p><ul><li><a href="https://ope.ed.gov/dapip/" rel="noopener noreferrer" target="_blank">U.S. Department of Education: DAPIP Database</a></li><li><a href="https://www.chea.org/" rel="noopener noreferrer" target="_blank">Council for Higher Education Accreditation (CHEA)</a></li><li><a href="https://discoveruni.gov.uk/course-comparison/" rel="noopener noreferrer" target="_blank">Discover Uni: Course Comparison</a></li><li><a href="https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/designated-learning-institutions-list.html" rel="noopener noreferrer" target="_blank">Government of Canada: DLI List</a></li><li><a href="https://cricos.education.gov.au/" rel="noopener noreferrer" target="_blank">Australian Government: CRICOS Register</a></li></ul></section>
'''

start_marker = '<article class="article-body">'
end_marker = '<div class="author-bio-box"'

start_idx = html.find(start_marker) + len(start_marker)
end_idx = html.find(end_marker)

if start_idx != -1 and end_idx != -1:
    updated_html = html[:start_idx] + new_content + html[end_idx:]
    with open('how-to-verify-university-accreditation-before-you-apply/index.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)
    print("Accreditation article successfully updated!")
else:
    print("Markers not found!")