import re
import os

updates = {
    r'university-of-waterloo-admissions-fees-ranking-co-op-programs-for-international-students\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions for International Students</h2><details><summary>Is the University of Waterloo co-op mandatory?</summary><p>For many highly competitive programs, such as Engineering and Mathematics, the co-op stream is heavily integrated and practically mandatory for the best career outcomes. However, regular streams exist for some faculties (like Arts or Science), though the co-op experience is Waterloo's primary advantage in the Canadian job market.</p></details><details><summary>How competitive is Waterloo Engineering for international students?</summary><p>It is exceptionally competitive. Waterloo Engineering requires an extremely high high school average (often 90%+ or equivalent), strong scores on the Advanced Information Form (AIF), and participation in optional but highly recommended math or computing contests (like the Euclid Mathematics Contest).</p></details><details><summary>Does Waterloo offer significant scholarships for international students?</summary><p>While Waterloo does offer entrance scholarships (ranging from \,000 to \,000 CAD), they rarely cover the full cost of international tuition. Students should expect to fund the majority of their education, though co-op earnings during work terms can significantly offset living expenses.</p></details></section>''',

    r'top-15-ivy-league-alternatives\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About Ivy Alternatives</h2><details><summary>What makes a school an Ivy League alternative?</summary><p>An Ivy League alternative (often referred to as an "Ivy Plus," "Hidden Ivy," or "Public Ivy") is a university that matches or exceeds the Ivy League in academic rigor, endowment size, faculty quality, and graduate outcomes, but simply does not belong to the historic athletic conference that defines the Ivy League.</p></details><details><summary>Are Public Ivies cheaper than actual Ivy League schools?</summary><p>If you are an in-state resident, yes, Public Ivies (like UC Berkeley, UVA, or Michigan) are significantly cheaper. However, if you are an out-of-state or international applicant, the tuition at these public institutions can be nearly as high as private Ivy League schools, and they often offer less need-based financial aid for non-residents.</p></details><details><summary>Do Ivy League alternatives have higher acceptance rates?</summary><p>Not necessarily. Schools like Stanford, MIT, and Caltech have acceptance rates that are often lower than several Ivy League schools (like Cornell or Dartmouth). However, some excellent alternatives (like large state flagships) may have slightly higher overall acceptance rates due to larger class sizes.</p></details></section>''',

    r'the-brearley-school-elite-nyc-all-girls-k-12-overview\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About The Brearley School</h2><details><summary>How competitive is the admissions process for Brearley?</summary><p>Admissions to Brearley are famously competitive, particularly for the Kindergarten and 9th-grade entry points. The school looks for exceptionally curious, intellectually driven girls and requires standardized testing (like the ISEE or SSAT for older grades), interviews, and strong school reports.</p></details><details><summary>What is the academic culture like at Brearley?</summary><p>Brearley is known for its rigorous, traditional, and intense academic environment. The curriculum is deeply grounded in the liberal arts, and students are expected to handle a heavy reading and writing workload. It is widely considered one of the most academically demanding independent schools in the United States.</p></details><details><summary>Does Brearley offer financial aid?</summary><p>Yes, Brearley is committed to maintaining a socioeconomically diverse student body and offers significant need-based financial aid. Families must apply for aid simultaneously with their admissions application, and decisions are made based on the family's demonstrated financial need.</p></details></section>''',

    r'queens-university-canada-admissions-fees-ranking-programs-student-life\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions for Prospective Queen's Students</h2><details><summary>What is Queen's University best known for academically?</summary><p>Queen's University, located in Kingston, Ontario, is particularly renowned for the Smith School of Business (specifically its highly competitive Commerce program), its robust Engineering curriculum, and strong Health Sciences and Nursing programs.</p></details><details><summary>Is Kingston a good city for international students?</summary><p>Kingston is often described as the quintessential Canadian "university town." It is smaller, safer, and highly student-focused compared to massive urban centers like Toronto or Vancouver. The vast majority of students live within a 15-minute walk of the campus, creating an incredibly tight-knit and vibrant student community.</p></details><details><summary>What is the Queen's Personal Statement of Experience (PSE)?</summary><p>For many competitive programs, Queen's requires or highly recommends the submission of a Personal Statement of Experience (PSE) or supplementary essay. This allows the admissions committee to evaluate a student's extracurricular leadership, community involvement, and character, rather than relying solely on high school grades.</p></details></section>''',

    r'university-of-chicago-complete-guide\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About UChicago</h2><details><summary>What is the UChicago Core Curriculum?</summary><p>The Core Curriculum is the defining feature of a UChicago undergraduate education. It is a rigorous set of required courses spanning the humanities, social sciences, physical and biological sciences, and mathematics. It forces all students, regardless of their major, to engage in deep intellectual debate and read foundational primary texts.</p></details><details><summary>Is UChicago as stressful as its reputation suggests?</summary><p>UChicago proudly embraces its reputation as an intense intellectual environment (often jokingly referred to as "the place where fun comes to die"). However, students generally find the environment more highly collaborative and deeply nerdy than cutthroat competitive. The university has also heavily invested in student wellness and campus life in recent years.</p></details><details><summary>What are the uncommon essay prompts?</summary><p>UChicago is famous for its eccentric and highly creative supplemental essay prompts. Past prompts have asked students to compare apples and oranges or discuss what they would do with a newly discovered planet. The admissions team uses these to identify students who genuinely love thinking outside the box.</p></details></section>''',

    r'university-of-alberta-admissions-fees-ranking-programs-for-international-students\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About UAlberta</h2><details><summary>What is the University of Alberta best known for?</summary><p>UAlberta is globally recognized for its exceptional research and programs in Engineering, Energy (oil, gas, and renewables), Paleontology, Artificial Intelligence, and Agriculture. Its location in Edmonton makes it a major hub for Canada's energy sector.</p></details><details><summary>How cold does it actually get in Edmonton?</summary><p>Edmonton experiences harsh, extremely cold winters, with temperatures frequently dropping below -20°C (-4°F) from December to February. However, the university campus is well-adapted to the climate, featuring extensive indoor connections (pedways) between major buildings.</p></details><details><summary>Does UAlberta offer good scholarships for international students?</summary><p>Yes, compared to many other top-tier Canadian universities, the University of Alberta offers a relatively generous range of entrance and merit-based scholarships for international students, which can help significantly offset the cost of tuition.</p></details></section>''',
    
    r'where-is-columbia-university-in-nyc-the-ultimate-2026-location-campus-guide\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About Columbia's Location</h2><details><summary>Is Morningside Heights a safe neighborhood for students?</summary><p>Yes, Morningside Heights is generally considered a very safe neighborhood in Manhattan. It is heavily populated by students, faculty, and young professionals. Columbia University also employs a robust Public Safety department that patrols the campus and surrounding blocks 24/7, and provides evening shuttle services.</p></details><details><summary>Do Columbia students have time to explore New York City?</summary><p>While the Core Curriculum and academic workload are notoriously demanding, most Columbia students actively engage with the city. The university offers discounted tickets to Broadway shows, museums (like the Met and MoMA), and cultural events, actively encouraging students to use NYC as an extension of the classroom.</p></details><details><summary>Are freshmen required to live on campus?</summary><p>Yes, all first-year undergraduate students at Columbia College and the School of Engineering are required to live on campus. Almost all upperclassmen also choose to remain in university-owned housing for all four years because securing a private apartment in Manhattan is extraordinarily expensive and complex.</p></details></section>''',

    r'cornell-university-an-honest-student-perspective-2026-guide\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About Cornell</h2><details><summary>What is the difference between Cornell's state and endowed colleges?</summary><p>Cornell is unique in the Ivy League because it is a hybrid institution. It operates privately endowed colleges (like Arts & Sciences and Engineering) alongside publicly supported statutory colleges (like Agriculture & Life Sciences, and Industrial & Labor Relations). New York State residents receive significantly reduced tuition if they enroll in one of the statutory colleges.</p></details><details><summary>Is Ithaca really as isolated as people say?</summary><p>Ithaca is located in upstate New York, about a four-hour drive from New York City. While it is geographically isolated compared to urban Ivies like Columbia or UPenn, Ithaca is a vibrant, quintessential college town surrounded by stunning gorges and waterfalls. The isolation fosters an incredibly tight-knit campus community.</p></details><details><summary>How bad is the grade deflation at Cornell?</summary><p>Cornell has a historical reputation for intense academic rigor and strict grading curves, particularly in pre-med and engineering prerequisite courses. While "grade deflation" is heavily debated, students should expect that earning an 'A' requires significantly more effort than at some peer institutions that are known for grade inflation.</p></details></section>''',

    r'why-choose-mcmaster-university-in-canada-fees-ranking-career-opportunities\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About McMaster</h2><details><summary>What is the 'McMaster Model' of education?</summary><p>McMaster University is world-famous for pioneering Problem-Based Learning (PBL). Instead of traditional memorization-heavy lectures, the McMaster Model focuses on small-group tutorials where students are presented with real-world, open-ended problems and must research, collaborate, and discover the solutions themselves.</p></details><details><summary>How hard is it to get into McMaster's Health Sciences program?</summary><p>The Bachelor of Health Sciences (BHSc) program at McMaster is arguably the most competitive undergraduate program in Canada, often boasting acceptance rates lower than 5%. It is highly sought after because an extraordinarily high percentage of its graduates successfully gain admission to medical school.</p></details><details><summary>Is Hamilton a good student city?</summary><p>Hamilton, Ontario, is a rapidly revitalizing city located about an hour from Toronto. It offers a much lower cost of living than Toronto, a thriving arts and culinary scene, and incredible access to nature (it is known as the "Waterfall Capital of the World"). The campus itself is tucked against the scenic Royal Botanical Gardens.</p></details></section>''',

    r'what-is-northwestern-university-known-for-the-2026-insider-guide\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About Northwestern</h2><details><summary>What are the most famous programs at Northwestern?</summary><p>Northwestern is perhaps best known globally for the Medill School of Journalism and the Kellogg School of Management. At the undergraduate level, it also boasts elite programs in Communications (particularly Theater and Film), Engineering, Economics, and the Bienen School of Music.</p></details><details><summary>What is the 'Quarter System' at Northwestern?</summary><p>Unlike most universities that use a two-semester academic calendar, Northwestern operates on a fast-paced quarter system. Students typically take four classes over three 10-week terms (Fall, Winter, Spring). This allows students to take a wider variety of classes and easily double major, but it requires highly consistent study habits as midterms arrive very quickly.</p></details><details><summary>How is the campus vibe in Evanston?</summary><p>Evanston is an affluent, safe, and beautiful suburb immediately north of Chicago, located right on the shores of Lake Michigan. Students get the best of both worlds: a traditional, leafy, Big Ten college campus experience with private beaches, combined with a quick 45-minute train ride directly into the heart of downtown Chicago.</p></details></section>''',

    r'massachusetts-institute-of-technology-complete-overview-key-facts-and-official-contact-details\\index.html': '''<section class="faq-section"><h2>Frequently Asked Questions About MIT</h2><details><summary>Does MIT only focus on STEM?</summary><p>While MIT is undisputedly the global leader in Science, Technology, Engineering, and Mathematics, it is not strictly a STEM-only school. It boasts highly prestigious programs in Economics, Political Science, Linguistics, and the Sloan School of Management. All undergraduates must also complete a rigorous Humanities, Arts, and Social Sciences (HASS) requirement.</p></details><details><summary>What is the MIT Independent Activities Period (IAP)?</summary><p>IAP is a unique four-week term in January. During this time, standard classes are suspended, and students are encouraged to pursue independent research, take quirky micro-classes (like glassblowing or advanced cryptography), complete intensive mini-internships, or travel abroad. It is a beloved MIT tradition.</p></details><details><summary>How intense is the workload at MIT?</summary><p>MIT is famous for the phrase "drinking from a firehose." The academic rigor and volume of work assigned are exceptionally high. However, the culture is famously collaborative rather than cutthroat. Students survive the workload by forming tight-knit study groups (Psets) and utilizing the university's robust academic support networks.</p></details></section>'''
}

for filepath, new_content in updates.items():
    # Because of windows path separators, use generic search
    filename = filepath.split('\\\\')[-1]
    
    # find actual file in directory tree
    actual_path = None
    for root, dirs, files in os.walk('.'):
        if 'index.html' in files and filepath.split('\\\\')[0] in root:
            actual_path = os.path.join(root, 'index.html')
            break
            
    if actual_path:
        with open(actual_path, 'r', encoding='utf-8') as f:
            html = f.read()
        
        # Inject before <section class="source-section"> if possible, or before </article>
        if '<section class="source-section">' in html:
            html = html.replace('<section class="source-section">', new_content + '\n<section class="source-section">')
            with open(actual_path, 'w', encoding='utf-8') as f:
                f.write(html)
            print(f"Updated {actual_path}")
        else:
            print(f"Could not find source section in {actual_path}")
    else:
        print(f"Could not find {filepath}")