import re

with open('how-to-verify-an-australian-cricos-course/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# I will locate the content to replace. 
# It starts right after <article class="article-body"> and ends right before <div class="author-bio-box"
new_content = '''<div class="answer-box"><span>Quick answer</span><p>Search the exact provider or course in the Australian Government CRICOS register, then match the course code, provider code, campus, duration and level with your offer and the institution's official page. Never accept an offer or pay a deposit for an Australian student visa unless the course is actively registered.</p></div><div class="editor-note"><strong>Editorial note:</strong> Education, admissions, fees and immigration rules can change. Check the linked official source again before applying or paying.</div>

<section><h2>What CRICOS is and Why It Exists</h2><p>The Commonwealth Register of Institutions and Courses for Overseas Students (CRICOS) is the Australian Government's official database. It lists all Australian education providers offering courses to people studying in Australia on student visas, as well as the specific courses they are permitted to offer.</p><p>Under Australian law—specifically the Education Services for Overseas Students (ESOS) Act—any institution offering education to international students must be registered on CRICOS. This framework is designed to protect international students, ensuring high educational standards and providing financial protection if a provider closes or fails to deliver the promised course.</p><p>It is the absolute correct starting point for checking whether the provider and course are legitimate. A university ranking page, an education agent's list, or a polished marketing brochure is never a substitute for the official government register. Note that CRICOS registration simply indicates compliance with the ESOS framework; it does not guarantee admission, a student visa, or future employment outcomes.</p></section>

<section><h2>The ESOS Framework: Your Rights as an International Student</h2><p>CRICOS operates under the broader umbrella of the ESOS Framework. Understanding this framework is crucial because it legally outlines your rights and the responsibilities of your education provider.</p><p>The ESOS Framework guarantees the following protections:</p><ul><li><strong>Quality Assurance:</strong> Providers must meet strict national standards in marketing, student support, and academic delivery.</li><li><strong>Tuition Protection Service (TPS):</strong> If your institution closes or cannot deliver your course, the TPS ensures you can either complete your studies at another institution or receive a refund for unspent tuition fees.</li><li><strong>Accurate Information:</strong> Providers and their agents are legally required to provide accurate information regarding course details, costs, and campus locations.</li></ul></section>

<section><h2>Step-by-Step: How to Search the CRICOS Register</h2><p>Verifying a course takes only a few minutes but can save you from severe financial and immigration issues. Use the official CRICOS website (cricos.education.gov.au) and follow these steps:</p><h3>1. Search using the strongest identifier (CRICOS Course Code)</h3><p>Every registered course has a unique CRICOS course code (e.g., 012345A). If your letter of offer or the university's course page shows a CRICOS code, enter it directly into the Course Search tool. This is the most accurate way to verify registration because it prevents confusion between similarly named degrees.</p><h3>2. Search by Provider Name or Code</h3><p>If you don't have the course code, search using the institution's legal provider name or CRICOS Provider Code. Be aware that many Australian universities have multiple campuses (e.g., Sydney, Melbourne, regional campuses) and sometimes operate through third-party pathway providers. Name-only matching is often insufficient.</p><h3>3. Check the Registration Status</h3><p>Ensure the provider and the specific course are listed as "Active." If a course is listed as "Suspended" or "Cancelled," the provider cannot legally offer it to new international students.</p></section>

<section><h2>Match These Exact Fields on Your Offer Letter</h2><p>Once you locate the course on CRICOS, compare the official register data line-by-line with your offer letter and the institution's current course page. Do not pay any tuition deposits until you have confirmed the following details:</p><ul><li><strong>Provider Name and Provider Code:</strong> Does the legal name match the entity requesting payment?</li><li><strong>Course Title and CRICOS Course Code:</strong> Is it the exact degree you applied for? (e.g., Master of Business vs. Master of Business Administration).</li><li><strong>Qualification Level:</strong> Is it a Bachelor, Master, or Diploma? Ensure it matches the Australian Qualifications Framework (AQF) level you expect.</li><li><strong>Campus or Delivery Location:</strong> Many universities partner with private colleges to deliver courses in different cities. Ensure the CRICOS record registers the course at the specific campus you plan to attend.</li><li><strong>Registered Duration:</strong> How many weeks or years is the course registered for? This directly affects your student visa duration.</li><li><strong>Work Component / Practicum:</strong> If your course includes mandatory clinical placements or internships, check if it is noted in the registration.</li></ul></section>

<section><h2>Red Flags: When to Stop Your Application</h2><p>Unfortunately, international students are sometimes targeted by fraudulent operators or misinformed agents. Stop your application process immediately if you encounter any of the following scenarios:</p><ul><li>The course or provider cannot be located in the CRICOS register.</li><li>The CRICOS course code on your offer belongs to a different provider, a different course, or a different campus location.</li><li>Your offer letter omits the CRICOS code entirely, and the provider or agent refuses to clarify it in writing.</li><li>You are instructed to study a "non-award" or non-CRICOS course while on a Subclass 500 Student Visa. (This is generally a breach of visa conditions).</li><li>A third-party agent guarantees a visa approval or a job in Australia in exchange for enrolling in a specific unregistered college.</li><li>Payment is requested through a personal bank transfer or a channel that the official university website does not endorse.</li></ul></section>

<section><h2>Adding Quality and Outcome Context</h2><p>CRICOS tells you if a course is legal; it does not tell you if the course is high quality. After confirming the registration, use tools like QILT (Quality Indicators for Learning and Teaching) and ComparED to evaluate student experience and graduate outcomes across Australian higher education.</p><p>QILT publishes comparison data derived from the official Student Experience Survey (SES) and Graduate Outcomes Survey (GOS). This data is funded by the Australian Government and provides transparent metrics on teaching quality, skills development, and graduate employment rates.</p><p>However, always interpret results with published context. Response rates, specific subject groupings, institution size, and regional labour markets can significantly affect comparisons. Use QILT data to form smart questions for university representatives, rather than treating the numbers as a guaranteed outcome for your own career.</p></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Does a CRICOS listing guarantee a student visa?</summary><p>No. CRICOS merely confirms the legal registration status of the education provider and the course. The Department of Home Affairs independently assesses your visa application under current immigration rules, evaluating factors like Genuine Student (GS) requirements, financial capacity, and English proficiency.</p></details><details><summary>Why is matching the exact campus so important?</summary><p>Providers frequently operate across multiple locations or partner with third parties in different cities. A university might be registered to offer a Master of IT in Sydney but not in Melbourne. If you accept an offer for an unregistered location, your visa application may be refused.</p></details><details><summary>Can I study a non-CRICOS course on a student visa?</summary><p>Generally, no. The primary course of study for a Subclass 500 Student Visa must be registered on CRICOS. There are very limited exceptions for supplementary short courses, but your main enrollment must be CRICOS-approved.</p></details><details><summary>What is the difference between TEQSA, ASQA, and CRICOS?</summary><p>TEQSA (Tertiary Education Quality and Standards Agency) regulates higher education providers (universities). ASQA (Australian Skills Quality Authority) regulates vocational education and training (VET). CRICOS is the actual database where TEQSA and ASQA record the providers and courses they have approved for international students.</p></details><details><summary>Can QILT replace a CRICOS check?</summary><p>No. QILT adds student-experience and outcomes context. CRICOS is the official, legal course and provider register for overseas students. Always perform the CRICOS check first.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026. Please verify directly with official portals for the most up-to-date regulations.</p><ul><li><a href="https://cricos.education.gov.au/" rel="noopener noreferrer" target="_blank">Australian Government CRICOS Database</a></li><li><a href="https://www.education.gov.au/esos-framework" rel="noopener noreferrer" target="_blank">Department of Education: ESOS Framework</a></li><li><a href="https://www.qilt.edu.au/" rel="noopener noreferrer" target="_blank">QILT (Quality Indicators for Learning and Teaching)</a></li><li><a href="https://www.qilt.edu.au/comparED" rel="noopener noreferrer" target="_blank">QILT ComparED Platform</a></li></ul></section>
'''

start_marker = '<article class="article-body">'
end_marker = '<div class="author-bio-box"'

start_idx = html.find(start_marker) + len(start_marker)
end_idx = html.find(end_marker)

if start_idx != -1 and end_idx != -1:
    updated_html = html[:start_idx] + new_content + html[end_idx:]
    with open('how-to-verify-an-australian-cricos-course/index.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)
    print("CRICOS article successfully updated!")
else:
    print("Markers not found!")