import re

with open('how-to-choose-a-university-course-uk/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

new_content = '''<div class="answer-box"><span>Quick answer</span><p>Choose a UK course by comparing its modules, teaching methods, assessment styles, placement options, entry requirements, total cost, and official Discover Uni data. Do not assume that courses with the exact same title offer the same learning experience or professional accreditations. Build a shortlist based on curriculum fit first, and university reputation second.</p></div><div class="editor-note"><strong>Editorial note:</strong> Education, admissions, fees, and immigration rules can change. Check the linked official source again before applying or paying.</div>

<section><h2>Define the Subject Outcome and Accreditation You Need</h2><p>Begin with the knowledge, skills, or career direction you want rather than starting with a prestigious university name. In the UK higher education system, the specific curriculum is often more important than the institution's overall ranking.</p><p>Identify required core topics, optional specialisms, and crucially, whether you need professional accreditation. Many careers in the UK—such as Engineering, Psychology, Architecture, and Accounting—require degrees accredited by Professional, Statutory and Regulatory Bodies (PSRBs) like the BPS, RIBA, or IET. A highly ranked university might offer an unaccredited psychology degree, which would prevent you from practicing clinically without further study.</p><p>UCAS (the Universities and Colleges Admissions Service) explicitly notes that courses sharing the exact same title can vary wildly in content. The detailed module specification list should be one of the first documents you compare.</p></section>

<section><h2>Compare the Course Structure Line by Line</h2><p>Never rely solely on a university's marketing summary page. Dig into the course specifications. A standard UK undergraduate degree typically consists of 360 credits (120 credits per year). Ask the admissions team which modules are guaranteed to run and which are merely "indicative" (meaning they depend on student demand or staffing availability).</p><ul><li><strong>Core vs. Optional Modules:</strong> Does the course force you into a rigid structure, or can you tailor your degree with electives in your second and third years?</li><li><strong>Teaching Delivery:</strong> Look at the balance between large lectures, small-group seminars, laboratory practicals, studio time, and expected independent study hours.</li><li><strong>Assessment Styles:</strong> If you struggle with exams, look for courses heavily weighted towards coursework, practical assessments, presentations, and group projects.</li><li><strong>Placement Years (Sandwich Degrees):</strong> Does the course offer an integrated year in industry or a year abroad? These "sandwich years" drastically improve graduate employability.</li><li><strong>Flexibility:</strong> What are the rules for changing pathways after enrollment? Can you easily switch from a BA to a BSc, or from a single honors to a joint honors degree?</li></ul></section>

<section><h2>Use Discover Uni and the TEF as Evidence, Not a Verdict</h2><p>Discover Uni is the UK government's official course comparison tool. It lets applicants compare official course data and clearly explains where the information comes from, primarily drawing from the National Student Survey (NSS) and Graduate Outcomes data.</p><p>You should also review the Teaching Excellence Framework (TEF) ratings (Gold, Silver, or Bronze) which assess teaching quality and student outcomes at the provider level.</p><p>However, review student experience, continuation rates, and graduate outcomes together, paying close attention to the cohort size and response rate. Be aware of notes indicating that data has been grouped from related courses due to small class sizes. A raw percentage does not tell the whole story. Use it to form targeted questions for the department at an open day—for example, asking how assessment feedback works or which specific employers recruited recent graduates.</p></section>

<section><h2>Check Entry Requirements and Contextual Offers</h2><p>Compare the required subjects, typical grade ranges (e.g., AAB at A-Level or 34 IB points), English-language evidence (IELTS/TOEFL requirements), and any portfolio or interview prerequisites.</p><p>It is vital to understand the difference between standard offers and <strong>contextual offers</strong>. Many UK universities lower their grade requirements by one or two grades for applicants from disadvantaged backgrounds or underrepresented areas. Check if you are eligible for a contextual offer using the university's online calculator.</p><p>For international qualifications, use the university's dedicated country page and request written clarification from the international admissions team if your specific high school curriculum is not listed. Finally, do not assume that merely meeting the published minimum requirements guarantees an offer. Competitive selection, subject combinations, and the sheer volume of applicants for courses like Medicine or Computer Science play a massive role.</p></section>

<section><h2>Test the Practical Fit: City vs. Campus</h2><p>The academic course is only half the experience. The location and practical setup of the university will define your daily life for three to four years.</p><ul><li><strong>Campus vs. City:</strong> Do you want a self-contained campus university (where everything is in one place) or a city university (where buildings are spread across a bustling urban center)?</li><li><strong>Financial Stress-Test:</strong> Can you afford the full course and location under a realistic budget? Living costs in London or the South East are drastically higher than in the North of England or Wales.</li><li><strong>Support Services:</strong> Are disability, mental health, wellbeing, and academic-support services well-funded and easily accessible?</li><li><strong>Accommodation:</strong> Is university-owned accommodation guaranteed for first-year students? What is the private rental market like for second and third-year students?</li><li><strong>Careers Support:</strong> What specific careers support is embedded within your academic department, rather than just the generic university-wide careers service?</li></ul></section>

<section><h2>Create a Final Evidence Table</h2><p>For each shortlisted course, create a spreadsheet recording the official course link, the date you checked it, the module fit score, total tuition and estimated living costs, entry risk (reach vs. safety school), outcome evidence, and two unanswered questions to ask at an open day.</p><p>Score the courses only after this evidence table is complete. A transparent, data-driven table makes it much easier to objectively explain the choice to yourself and prevents a university's historical reputation from overshadowing your actual research.</p></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Are courses with the exact same title equivalent across different UK universities?</summary><p>Absolutely not. Modules, assessment methods, teaching contact hours, industry placements, and professional recognition can differ substantially. A "Business Management" degree at one university might be heavily mathematical, while at another, it might focus on human resources and theory.</p></details><details><summary>Is Discover Uni a university ranking?</summary><p>No. It is an official government-backed course-information and comparison service. Its data should be interpreted with the published context and limitations, not used as a definitive league table.</p></details><details><summary>Is a degree from a Russell Group university automatically better?</summary><p>Not necessarily. While Russell Group universities are highly prestigious and research-intensive, many non-Russell Group universities excel in teaching quality (often scoring TEF Gold), offer better industry placements, and hold higher rankings for specific subjects like Art, Design, Nursing, or specialized Engineering.</p></details><details><summary>Should I choose the course or the university first?</summary><p>For most applicants, it is highly recommended to define the subject, professional accreditation, and course requirements first, and then compare the institutions that actually meet those specific academic needs.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026. Please verify directly with official portals for the most up-to-date regulations.</p><ul><li><a href="https://www.ucas.com/applying/you-apply/what-and-where-study/choosing-course" rel="noopener noreferrer" target="_blank">UCAS: Choosing a Course</a></li><li><a href="https://www.ucas.com/applying/before-you-apply/what-and-where-to-study/choosing-a-course/comparing-undergraduate-courses-and-unis" rel="noopener noreferrer" target="_blank">UCAS: Comparing Courses and Universities</a></li><li><a href="https://discoveruni.gov.uk/course-comparison/" rel="noopener noreferrer" target="_blank">Discover Uni: Course Comparison Tool</a></li><li><a href="https://discoveruni.gov.uk/about-our-data/" rel="noopener noreferrer" target="_blank">Discover Uni: Understanding the Data</a></li></ul></section>
'''

start_marker = '<article class="article-body">'
end_marker = '<div class="author-bio-box"'

start_idx = html.find(start_marker) + len(start_marker)
end_idx = html.find(end_marker)

if start_idx != -1 and end_idx != -1:
    updated_html = html[:start_idx] + new_content + html[end_idx:]
    with open('how-to-choose-a-university-course-uk/index.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)
    print("UK article successfully updated!")
else:
    print("Markers not found!")