import re

updates = {
    'college-ranking-red-flags-and-how-to-read-them/index.html': '''<div class="answer-box"><span>Quick answer</span><p>Trust a ranking only when it clearly identifies the population, data year, sources, indicators, weights, missing-data treatment and limitations. Treat unexplained scores and exact positions as editorial claims, not objective facts. Always verify outcomes using official government data instead of commercial publisher lists.</p></div><div class="editor-note"><strong>Editorial note:</strong> Education, admissions, fees and immigration rules can change. Check the linked official source again before applying or paying.</div>

<section><h2>A Ranking is a Model, Not a Fact Sheet</h2><p>Every commercial university ranking turns millions of data points into a single, highly simplified ordered list. The publisher makes subjective choices about what data to include, how to normalize it, and how much weight each factor carries. A completely different set of methodological choices can produce a wildly different order without either table containing a mathematical error.</p><p>You should use rankings primarily to discover options, build shortlists, and formulate questions for admissions officers. Do not let a composite "score" replace course-level research, official government graduate outcomes data, or your personal academic fit.</p></section>

<section><h2>Red Flag 1: The "Universe" of Eligible Schools is Unclear</h2><p>A legitimate ranking must explicitly define its population: Are they measuring all accredited universities globally? Only research-intensive universities? Only boarding schools? Only institutions that paid a fee to supply data? If the universe of schools is unclear, a claim like "Top 10 in the Region" might literally mean "Top 10 among an undisclosed shortlist of 15 schools." Always check the eligibility criteria before trusting a ranking badge.</p></section>

<section><h2>Red Flag 2: Data Sources and Dates are Missing</h2><p>Look carefully for the original dataset, publication year, and the date the data was collected. Many commercial rankings combine reputation surveys from two years ago, institutional submissions from last year, and public statistics from three years ago. A "2026 Edition" title does not mean the data reflects the 2026 academic year. If the publisher hides the data collection window, the ranking is unreliable.</p></section>

<section><h2>Red Flag 3: Weights Have No Logical Rationale</h2><p>A transparent methodology will disclose all indicators and their exact percentage weights. But you must ask whether those weights actually represent your personal goals. For example, the QS World University Rankings historically placed massive weight on academic reputation and research citations. This formula is highly useful for comparing PhD research intensity, but it is almost entirely useless for choosing an undergraduate teaching environment where class sizes and student support matter more.</p></section>

<section><h2>Red Flag 4: False Precision and Marginal Differences</h2><p>Adjacent institutions often have nearly identical underlying scores, even when the published list presents a dramatic difference between positions. Check the raw score gaps, ties, and statistical uncertainty where available. A university moving from rank #14 to #11 does not automatically demonstrate a meaningful institutional improvement; it usually just reflects a minor statistical anomaly or a change in the publisher's formula.</p></section>

<section><h2>Red Flag 5: The "Black Box" of Missing Data</h2><p>Good methodologies explain exactly how missing, anomalous, or incomparable data is treated. Substituting a national average, excluding an institution entirely, or assigning an arbitrary penalty can each drastically change the final order. If a publisher is silent on how they handle missing data, their results are impossible to reproduce and should be treated with deep skepticism.</p></section>

<section><h2>The Six-Question Ranking Check</h2><p>Before you let a ranking influence your university choice, apply this six-question test. If the answer to several of these questions is "No" or "I don't know," use the list only as a preliminary discovery tool.</p><ul><li>Which specific institutions and programs were eligible for inclusion?</li><li>What specific academic year and original source supports each indicator?</li><li>How are the raw metrics normalized and weighted into a final score?</li><li>How does the publisher handle missing data, ties, and small sample sizes?</li><li>Does this specific methodology actually measure the decision I am making (e.g., undergraduate teaching vs. postgraduate research)?</li><li>Can I independently confirm the ranking's most important claims using an official government source?</li></ul></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Can two highly reputable rankings strongly disagree?</summary><p>Yes, absolutely. Because different publishers (like THE, QS, and ARWU) use entirely different populations, data sources, indicators, and weights, they frequently produce vastly different results for the exact same university.</p></details><details><summary>Does a higher overall rank guarantee better teaching?</summary><p>Not necessarily. Most global rankings reward research output and global reputation, not classroom teaching quality. Always check whether teaching quality is measured directly (e.g., using the UK TEF) and whether that evidence applies to your exact course.</p></details><details><summary>How should a ranking be used safely to build a shortlist?</summary><p>Use a ranking to discover institutions you hadn't considered and to frame questions. Once your shortlist is built, completely ignore the ranking and verify the actual decision factors—curriculum, net cost, and outcomes—using official and course-level sources like Discover Uni or the College Scorecard.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026.</p><ul><li><a href="https://collegescorecard.ed.gov/compare/" rel="noopener noreferrer" target="_blank">College Scorecard official comparison data</a></li><li><a href="https://discoveruni.gov.uk/about-our-data/" rel="noopener noreferrer" target="_blank">Discover Uni data methodology</a></li><li><a href="https://www.qilt.edu.au/" rel="noopener noreferrer" target="_blank">QILT student experience and outcomes data</a></li></ul></section>
''',
    
    'where-is-columbia-university-in-nyc-the-ultimate-2026-location-campus-guide/index.html': '''<div class="answer-box"><span>Quick answer</span><p>Columbia University's main Morningside Heights campus is located in Upper Manhattan, New York City, bordered by Broadway, Amsterdam Avenue, West 114th Street, and West 120th Street. The separate Manhattanville campus is nearby, and the Medical Center is further north in Washington Heights.</p></div><div class="editor-note"><strong>Editorial note:</strong> Campus borders, shuttle routes, and visitor policies can change. Always check the official Columbia University map and visitor guidelines before planning a trip to New York City.</div>

<section><h2>The Morningside Heights Main Campus</h2><p>When people refer to "Columbia University," they are almost always talking about the historic Morningside Heights campus. Located in Upper Manhattan, this tightly integrated, 32-acre campus was designed by the famous architectural firm McKim, Mead & White in the late 19th century.</p><p>Unlike many urban universities that are fragmented and blended into the city streets (like NYU), Columbia features a distinct, traditional, closed-campus feel while still being located in the heart of one of the world's most vibrant cities. The main gates are located on Broadway and 116th Street.</p><p><strong>Key Boundaries:</strong> The campus spans from West 114th Street in the south to West 120th Street in the north, and from Broadway in the west to Amsterdam Avenue in the east. It houses the undergraduate Columbia College, the Fu Foundation School of Engineering and Applied Science, and several major graduate schools including Law, Business, and Journalism.</p></section>

<section><h2>The Manhattanville Campus Expansion</h2><p>Just a few blocks north of the historic main campus lies Columbia's massive modern expansion in the Manhattanville neighborhood. This state-of-the-art, 17-acre development stretches roughly from West 125th Street to West 133rd Street.</p><p>Manhattanville is the new home of the Columbia Business School (David Geffen Hall and Henry R. Kravis Hall), the Jerome L. Greene Science Center, and the Lenfest Center for the Arts. This campus represents Columbia's modern future, featuring striking glass architecture and open public spaces designed to integrate seamlessly with the surrounding West Harlem community.</p></section>

<section><h2>Columbia University Irving Medical Center (CUIMC)</h2><p>Students studying medicine, nursing, dentistry, or public health will spend their time at the Columbia University Irving Medical Center. This massive medical and research complex is located significantly further north in the Washington Heights neighborhood, approximately 50 blocks north of the Morningside campus (around West 168th Street).</p><p>CUIMC is co-located with NewYork-Presbyterian Hospital, providing students with unparalleled access to clinical training and world-class medical research facilities.</p></section>

<section><h2>Getting Around: Transport and Shuttles</h2><p>Navigating between Columbia's campuses and the rest of New York City is highly efficient. The university relies heavily on the MTA (Metropolitan Transportation Authority) subway system.</p><ul><li><strong>To Morningside Heights:</strong> Take the 1 train to the 116th Street–Columbia University station, which stops directly outside the main gates.</li><li><strong>To Manhattanville:</strong> Take the 1 train to the 125th Street station.</li><li><strong>To the Medical Center:</strong> Take the 1, A, or C trains to the 168th Street station.</li></ul><p>Additionally, Columbia operates a free Intercampus Shuttle system for students, faculty, and staff, running continuously between Morningside Heights, Manhattanville, CUIMC, and the Lamont-Doherty Earth Observatory in Palisades, NY.</p></section>

<section><h2>Safety and the Surrounding Neighborhood</h2><p>Morningside Heights is a bustling, residential neighborhood filled with students, academics, cafes, and bookstores. It is generally considered very safe, heavily patrolled by both the NYPD and Columbia University Public Safety.</p><p>The university maintains a heavy security presence, and access to many campus buildings requires a valid Columbia ID. The neighborhood offers incredible access to green spaces, bordered by Riverside Park to the west (overlooking the Hudson River) and Morningside Park to the east.</p></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Is Columbia University an open campus?</summary><p>Yes, the outdoor plazas and walkways of the Morningside Heights and Manhattanville campuses are generally open to the public during daylight hours. However, access to academic buildings, libraries, and dormitories requires a student or staff ID card.</p></details><details><summary>How far apart are the Morningside and Manhattanville campuses?</summary><p>They are very close. It is approximately a 10 to 15-minute walk (about half a mile) between the main gates of Morningside Heights and the heart of the Manhattanville campus.</p></details><details><summary>Does Columbia guarantee housing in NYC?</summary><p>Yes, Columbia College and Columbia Engineering guarantee housing for undergraduate students for all four years, provided they remain continuously enrolled. Most undergraduates live on or immediately adjacent to the Morningside Heights campus.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026.</p><ul><li><a href="https://visit.columbia.edu/" rel="noopener noreferrer" target="_blank">Columbia University Visitors Center</a></li><li><a href="https://maps.columbia.edu/" rel="noopener noreferrer" target="_blank">Official Columbia Campus Maps</a></li><li><a href="https://transportation.columbia.edu/" rel="noopener noreferrer" target="_blank">Columbia Transportation and Shuttles</a></li></ul></section>
''',

    'boarding-school-open-day-questions-checklist/index.html': '''<div class="answer-box"><span>Quick answer</span><p>Prepare questions that uncover the reality of boarding life beyond the marketing brochure. Ask about weekend schedules, mobile phone policies, mental health support, bullying protocols, and exactly who supervises the dormitories at night. The best questions require specific examples rather than generic yes/no answers.</p></div><div class="editor-note"><strong>Editorial note:</strong> School policies and staffing structures change frequently. Always confirm critical policies regarding student welfare in writing with the admissions director before enrolling.</p></div>

<section><h2>The Purpose of an Open Day</h2><p>An open day or campus tour is a heavily curated marketing event designed to show the boarding school in its best possible light. The student tour guides are hand-picked, the dorms are meticulously cleaned, and the faculty are prepared for standard questions.</p><p>Your goal is to politely but firmly probe beneath this polished surface. The questions you ask should focus on the actual lived experience of a 14-year-old student living away from home for the first time. Focus heavily on pastoral care, weekend downtime, and disciplinary realities.</p></section>

<section><h2>Questions About Pastoral Care and Wellbeing</h2><p>Academic excellence means nothing if a child is miserable or unsupported. These questions help determine the school's true safety net.</p><ul><li>Who exactly is on duty in the boarding house at 2:00 AM if a student is sick or having a panic attack? Are they teaching staff or dedicated houseparents?</li><li>How does the school handle homesickness during the difficult first three weeks of term? Can you give a specific example of the protocol?</li><li>What is the exact ratio of full-time school counsellors to boarding students? Are these counsellors available after standard school hours?</li><li>How is bullying, particularly cyberbullying, actively monitored and handled within the boarding houses?</li><li>What is the strict policy on mobile phones and laptops in bedrooms after lights out? How is this enforced?</li></ul></section>

<section><h2>Questions About Weekends and Downtime</h2><p>Many boarding schools look incredible on a Tuesday afternoon but feel like ghost towns on a Sunday morning if a large percentage of students go home for the weekend.</p><ul><li>What percentage of boarders actually stay on campus during a typical non-exeat (standard) weekend?</li><li>Are weekend activities mandatory or optional? Who organizes them?</li><li>If a student does not want to play competitive sports on a Saturday, what exact alternative activities are available to them?</li><li>How often are students allowed to leave the campus to visit the local town, and what is the supervision policy for these trips?</li></ul></section>

<section><h2>Questions About Academics and Prep (Homework)</h2><p>Boarding schools must balance rigorous academics with the need for downtime. Understand how evening study works.</p><ul><li>How is "prep" (homework) supervised in the evenings? Is it done in individual bedrooms or a communal study hall?</li><li>If a student is struggling with a specific subject like Maths, what structural support is available in the evenings? Do academic tutors visit the boarding houses?</li><li>How does the school communicate minor academic or behavioral issues to parents who live in a different country or time zone?</li></ul></section>

<section><h2>Questions to Ask the Student Tour Guide (Privately)</h2><p>Student guides are usually honest if asked specific, relatable questions away from faculty ears.</p><ul><li>What is the absolute best and worst thing about the food here? What do you eat on a Sunday evening?</li><li>If you have a problem with a teacher or another student, who is the first person you actually go to for help?</li><li>What happens if you break a minor rule, like being late for roll call?</li><li>What do most boarders actually do on a Sunday afternoon here?</li></ul></section>

<section><h2>Creating Your Decision Matrix</h2><p>Do not rely on memory. Immediately after leaving the campus, sit in the car and write down your impressions while they are fresh. Score the school on safety, warmth of the houseparents, honesty of the student guides, and the quality of the facilities. If a school gives evasive or defensive answers to your wellbeing questions, it is a massive red flag that should override any academic ranking.</p></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Should the prospective student attend the open day?</summary><p>Yes, absolutely. The child is the one who will be living there. Their intuitive feeling about the campus vibe and the friendliness of the current students is often the most accurate indicator of whether they will thrive.</p></details><details><summary>Is it appropriate to ask about disciplinary statistics?</summary><p>Yes. You are fully within your rights to ask how many students were suspended or expelled in the previous academic year and for what primary reasons (e.g., vaping, bullying, academic dishonesty). Transparency here is a sign of a healthy school culture.</p></details><details><summary>What if we cannot visit in person because we live overseas?</summary><p>Request a live 1-on-1 virtual tour where a student walks around with an iPad or phone. Crucially, ask for a private Zoom meeting with the specific Housemaster or Housemistress who will be responsible for your child's dorm, not just the admissions director.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026.</p><ul><li><a href="https://www.ucas.com/applying/before-you-apply/what-and-where-to-study/choosing-a-course/comparing-undergraduate-courses-and-unis" rel="noopener noreferrer" target="_blank">UCAS comparison methodology applied to secondary education</a></li><li><a href="https://www.boardingschools.com/discover/the-boarding-school-advantage" rel="noopener noreferrer" target="_blank">The Association of Boarding Schools (TABS)</a></li></ul></section>
'''
}

for filepath, new_content in updates.items():
    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()
    
    start_marker = '<article class="article-body">'
    end_marker = '<div class="author-bio-box"'

    start_idx = html.find(start_marker) + len(start_marker)
    end_idx = html.find(end_marker)

    if start_idx != -1 and end_idx != -1:
        updated_html = html[:start_idx] + new_content + html[end_idx:]
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(updated_html)
        print(f"Updated {filepath}")
    else:
        print(f"Markers not found in {filepath}")