import re

with open('how-to-check-a-canadian-school-dli-before-applying/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

new_content = '''<div class="answer-box"><span>Quick answer</span><p>Search the current Government of Canada Designated Learning Institution (DLI) list online. Match the legal institution name, DLI number, and exact campus location. Crucially, confirm that your specific program at that campus makes you eligible for a Post-Graduation Work Permit (PGWP) before applying or paying any tuition fees.</p></div><div class="editor-note"><strong>Editorial note:</strong> Canadian education, admissions, fees, and immigration rules change frequently. Always check the linked official IRCC source again before applying or paying.</div>

<section><h2>What is a Designated Learning Institution (DLI)?</h2><p>In Canada, a Designated Learning Institution (DLI) is a school, college, or university approved by a provincial or territorial government to host international students. If you plan to study in Canada on a study permit for longer than six months, you must secure a Letter of Acceptance (LOA) from an approved DLI.</p><p>EduCanada and Immigration, Refugees and Citizenship Canada (IRCC) strictly enforce this requirement. If you apply for a Canadian study permit with an acceptance letter from a non-designated school, your visa application will be rejected.</p><p>However, understanding DLI status is only the first step. Being a DLI simply means the school is allowed to enroll international students. It does <strong>not</strong> guarantee a high-quality education, nor does it guarantee that you will be allowed to work in Canada after you graduate.</p></section>

<section><h2>The DLI Number vs. Post-Graduation Work Permit (PGWP) Eligibility</h2><p>One of the biggest misconceptions among international students is that attending any DLI automatically grants eligibility for a Post-Graduation Work Permit (PGWP). This is entirely false.</p><p>While all universities are DLIs, many private colleges and vocational schools are also DLIs but <strong>do not</strong> qualify for the PGWP program. Furthermore, recent IRCC rule changes have restricted PGWP eligibility for students attending private colleges that deliver public curriculum under licensing agreements (often called public-private partnerships).</p><p>When you check the official DLI list on the Government of Canada website, you must look at the column labeled "Offers PGWP-eligible programs." If this column says "No," you will not be able to apply for a post-graduation work permit after finishing your studies at that institution.</p></section>

<section><h2>Step-by-Step Guide: How to Verify the DLI List</h2><p>Verifying a school takes just a few minutes using the official IRCC portal. Never rely purely on an education agent's PDF brochure or a school's marketing website.</p><h3>1. Access the Official IRCC DLI Tool</h3><p>Navigate to the official Government of Canada website and locate the "Designated Learning Institutions list" search tool. Select the province or territory where the school is located.</p><h3>2. Search by Legal Name or DLI Number</h3><p>Many institutions operate under "trading names" that differ from their legal corporate names. If the name does not appear, ask the institution for their official "DLI Number" (which starts with an 'O', e.g., O19359011000) and type that into the search bar.</p><h3>3. Match the Exact Campus</h3><p>Some institutions have multiple campuses across different cities or provinces. A school might be an approved DLI with PGWP eligibility at its main campus in Toronto, but not at a satellite campus in another city. Ensure the specific campus you are applying to is explicitly listed and approved.</p></section>

<section><h2>Verify Program Details and Costs Directly</h2><p>While the EduCanada program search tool can help you build a shortlist of potential schools, it is not a legally binding document. You must confirm all academic and financial details directly with the institution.</p><p>Before signing an enrollment contract or transferring funds, open the official school website and verify:</p><ul><li><strong>Current Intake Dates:</strong> Is the program actually open for the semester you are applying for?</li><li><strong>Total Compulsory Charges:</strong> Beyond tuition, what are the mandatory fees for health insurance, student union access, and lab materials?</li><li><strong>Refund Policy:</strong> What happens to your deposit if your study permit is rejected? Legitimate DLIs have clear, publicly accessible refund policies for visa refusals.</li></ul><p>Always save the official fee schedule page. Do not rely on screenshots forwarded through WhatsApp or unauthorized third-party agent portals.</p></section>

<section><h2>Red Flags and Payment Safety Checklist</h2><p>International education fraud is a reality. Protect your investment by watching for these red flags:</p><ul><li>The school claims to be a DLI but refuses to provide their official DLI number.</li><li>An agent guarantees that enrolling in a specific private college will result in Canadian Permanent Residency (PR). Immigration is never guaranteed.</li><li>The school asks for tuition payments to be made via cryptocurrency, personal wire transfers, or unverified third-party apps.</li></ul><p><strong>Payment Safety Checklist:</strong></p><ul><li>Pay only through an institution-approved channel (e.g., Flywire, Convera, or direct bank transfer to the university's official corporate account).</li><li>Confirm the recipient name and currency before finalizing the transfer.</li><li>Keep all digital receipts and written communications with the admissions office.</li><li>Pause immediately if you feel pressured to pay a deposit before resolving discrepancies on your offer letter.</li></ul></section>

<section><h2>Recheck Immediately Before Visa Submission</h2><p>DLI statuses are not permanent. The Canadian government regularly audits institutions, and schools can lose their DLI status or PGWP eligibility if they fail to meet compliance standards.</p><p>Between the time you research a school, receive your admission offer, and finally apply for your study permit, the rules may have changed. Always perform one final check of the DLI list on the day you submit your study permit application to IRCC.</p></section>

<section class="faq-section"><h2>Frequently Asked Questions</h2><details><summary>Does DLI status guarantee a Canadian study permit?</summary><p>No. DLI status is a mandatory prerequisite, but it is only one part of the eligibility criteria. IRCC officers assess the full application, including your financial capacity, ties to your home country, and the logical progression of your studies.</p></details><details><summary>Does every program at a DLI offer a Post-Graduation Work Permit (PGWP)?</summary><p>No. Even at a PGWP-eligible DLI, certain short-term courses (under 8 months), language courses (ESL/FSL), and specific private college programs do not qualify for a PGWP. You must verify the specific program against current IRCC guidelines.</p></details><details><summary>Can I rely on an education agent's DLI screenshot?</summary><p>No. Screenshots can be easily manipulated or outdated. Always verify the current record yourself on the official Government of Canada website.</p></details><details><summary>What happens if my school loses its DLI status while I am studying?</summary><p>If your school loses its DLI status after you have already received your study permit, you can generally continue studying until your current permit expires. However, you will not be able to renew your study permit for that institution.</p></details></section>

<section class="source-section"><h2>Primary Sources</h2><p>Sources were accessed for this guide on 20 August 2026. Please verify directly with official portals for the most up-to-date regulations.</p><ul><li><a href="https://www.educanada.ca/study-plan-etudes/before-avant/apply-school_canada_demande-ecole.aspx?lang=eng" rel="noopener noreferrer" target="_blank">EduCanada: How to Apply to School</a></li><li><a href="https://w05.educanada.ca/" rel="noopener noreferrer" target="_blank">EduCanada Program Search</a></li><li><a href="https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/designated-learning-institutions-list.html" rel="noopener noreferrer" target="_blank">Government of Canada Official DLI List</a></li><li><a href="https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation/eligibility.html" rel="noopener noreferrer" target="_blank">IRCC: PGWP Eligibility Rules</a></li></ul></section>
'''

start_marker = '<article class="article-body">'
end_marker = '<div class="author-bio-box"'

start_idx = html.find(start_marker) + len(start_marker)
end_idx = html.find(end_marker)

if start_idx != -1 and end_idx != -1:
    updated_html = html[:start_idx] + new_content + html[end_idx:]
    with open('how-to-check-a-canadian-school-dli-before-applying/index.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)
    print("DLI article successfully updated!")
else:
    print("Markers not found!")