T1 = """<table><thead><tr><th>Niche rank</th><th>School</th><th>Location</th><th>Niche grade</th><th>Snapshot</th></tr></thead><tbody><tr><td>1</td><td>The Hotchkiss School</td><td>Lakeville, CT</td><td>A+</td><td>~611</td></tr><tr><td>2</td><td>Phillips Exeter Academy</td><td>Exeter, NH</td><td>A+</td><td>~1,096</td></tr><tr><td>3</td><td>Choate Rosemary Hall</td><td>Wallingford, CT</td><td>A+</td><td>~859</td></tr><tr><td>4</td><td>The Lawrenceville School</td><td>Lawrenceville, NJ</td><td>A+</td><td>House system</td></tr><tr><td>5</td><td>Groton School</td><td>Groton, MA</td><td>A+</td><td>Smaller cohort</td></tr><tr><td>6</td><td>Phillips Academy Andover</td><td>Andover, MA</td><td>A+</td><td>~1,164</td></tr><tr><td>7</td><td>St. Paul's School</td><td>Concord, NH</td><td>A+</td><td>Full boarding</td></tr><tr><td>8</td><td>Noble and Greenough School</td><td>Dedham, MA</td><td>A+</td><td>Day + boarding</td></tr><tr><td>9</td><td>Lake Forest Academy</td><td>Lake Forest, IL</td><td>A+</td><td>Midwest option</td></tr><tr><td>10</td><td>Cate School</td><td>Carpinteria, CA</td><td>A+</td><td>West Coast</td></tr><tr><td>11</td><td>St. Andrew's School</td><td>Middletown, DE</td><td>A+</td><td>Dead Poets campus</td></tr><tr><td>12</td><td>Oak Crest Academy – Pomona</td><td>Pomona, CA</td><td>A+</td><td>STEM-leaning</td></tr><tr><td>13</td><td>The Loomis Chaffee School</td><td>Windsor, CT</td><td>A+</td><td>CT corridor</td></tr><tr><td>14</td><td>The Peddie School</td><td>Hightstown, NJ</td><td>A+</td><td>NJ boarding</td></tr><tr><td>15</td><td>Deerfield Academy</td><td>Deerfield, MA</td><td>A+</td><td>Village campus</td></tr><tr><td>16</td><td>Milton Academy</td><td>Milton, MA</td><td>A+</td><td>Near Boston</td></tr><tr><td>17</td><td>American Heritage (Broward)</td><td>Plantation, FL</td><td>A+</td><td>Florida</td></tr><tr><td>18</td><td>Elite Preparatory Academy</td><td>Hopatcong, NJ</td><td>A+</td><td>NJ</td></tr><tr><td>19</td><td>The Village School</td><td>Houston, TX</td><td>A+</td><td>Texas</td></tr><tr><td>20</td><td>Princeton Int'l School of Math &amp; Science</td><td>Princeton, NJ</td><td>A+</td><td>STEM magnet</td></tr></tbody></table>"""
T2 = """<table>
<thead><tr><th>Stage</th><th>Typical timing</th><th>What to prepare</th></tr></thead>
<tbody>
<tr><td>Research &amp; tours</td><td>18–24 months before entry</td><td>Campus visits, virtual sessions, SSAT/ISEE planning</td></tr>
<tr><td>Registration</td><td>Fall before entry year</td><td>Parent forms, student essays, activity list</td></tr>
<tr><td>Testing &amp; recommendations</td><td>Oct–Jan</td><td>SSAT/ISEE, teacher/counsellor letters, transcripts</td></tr>
<tr><td>Interviews</td><td>Oct–Feb</td><td>On-campus or Zoom; practice thoughtful questions</td></tr>
<tr><td>Decisions</td><td>Mar 10 (common)</td><td>Compare aid packages; confirm visa steps</td></tr>
</tbody>
</table>"""
